package main

import "log"

func main() {
	// log.Println(Dazn(Ipv4HttpClient))
	// log.Println(Hotstar(Ipv4HttpClient))
	// log.Println(DisneyPlus(Ipv4HttpClient))
	// log.Println(NetflixRegion(Ipv4HttpClient), NetflixCDN(Ipv4HttpClient))
	// log.Println(YoutubeRegion(Ipv4HttpClient), YoutubeCDN(Ipv4HttpClient))
	// log.Println(PrimeVideo(Ipv4HttpClient))
	// log.Println(TVBAnywhere(Ipv4HttpClient))
	// log.Println(IqRegion(Ipv4HttpClient))
	// log.Println(ViuCom(Ipv4HttpClient))
	// log.Println(Spotify(Ipv4HttpClient))
	// log.Println(Steam(Ipv4HttpClient))
	// log.Println(ViuTV(Ipv4HttpClient))
	// log.Println(NowE(Ipv4HttpClient))
	// log.Println(MyTvSuper(Ipv4HttpClient))
	// log.Println(HboGoAisa(Ipv4HttpClient))
	// log.Println(BilibiliHKMCTW(Ipv4HttpClient))

	// log.Println(DMM(Ipv4HttpClient))
	// log.Println(Abema(Ipv4HttpClient))
	// log.Println(Niconico(Ipv4HttpClient))
	// log.Println(MusicJP(Ipv4HttpClient))
	// log.Println(Telasa(Ipv4HttpClient))
	// log.Println(Paravi(Ipv4HttpClient))
	// log.Println(U_NEXT(Ipv4HttpClient))
	// log.Println(HuluJP(Ipv4HttpClient))
	// log.Println(GYAO(Ipv4HttpClient))
	// log.Println(VideoMarket(Ipv4HttpClient))
	// log.Println(FOD(Ipv4HttpClient))
	// log.Println(Radiko(Ipv4HttpClient))
	// log.Println(Karaoke(Ipv4HttpClient))
	// log.Println(J_COM_ON_DEMAND(Ipv4HttpClient))
	// log.Println(Kancolle(Ipv4HttpClient))
	// log.Println(PrettyDerbyJP(Ipv4HttpClient))
	// log.Println(KonosubaFD(Ipv4HttpClient))
	// log.Println(PCRJP(Ipv4HttpClient))
	// log.Println(WFJP(Ipv4HttpClient))
	// log.Println(PJSK(Ipv4HttpClient))

	log.Println(KKTV(Ipv4HttpClient))
	log.Println(LiTV(Ipv4HttpClient))
	log.Println(MyVideo(Ipv4HttpClient))
	log.Println(TW4GTV(Ipv4HttpClient))
	log.Println(LineTV(Ipv4HttpClient))
	log.Println(HamiVideo(Ipv4HttpClient))
	log.Println(Catchplay(Ipv4HttpClient))
	log.Println(BahamuAnime(Ipv4HttpClient))
	log.Println(HboGoAisa(Ipv4HttpClient))
	log.Println(BilibiliTW(Ipv4HttpClient))
}
